# Generated by Django 4.1 on 2023-12-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_Condition', '0002_alter_room_fee_rate_alter_scheduler_fee_rate_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mode',
            field=models.IntegerField(choices=[(1, '制热'), (2, '制冷')], default=1, verbose_name='工作模式'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='mode',
            field=models.IntegerField(choices=[(1, '制热'), (2, '制冷')], default=1, verbose_name='工作模式'),
        ),
        migrations.AlterField(
            model_name='room',
            name='target_temp',
            field=models.FloatField(default=22.0, verbose_name='目标温度'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='default_target_temp',
            field=models.IntegerField(choices=[(22, '制热'), (25, '制冷')], default=22, verbose_name='默认目标温度'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='temp_high_limit',
            field=models.IntegerField(default=25, verbose_name='最高温度限制'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='temp_low_limit',
            field=models.IntegerField(default=18, verbose_name='最低温度限制'),
        ),
    ]
